version: '3.8'

services:
  otusdb:
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    expose:
      - "3306"
    ports:
      - "3309:3306"

  mysql-db-admin:
    image: adminer:4.8.1
    ports:
      - 80:8080


