version: '3.8'

services:
  otusdb:
    image: mysql:8.0.15
    environment:
      MYSQL_ROOT_PASSWORD: 12345
    command:
      --init-file /init.sql
    volumes:
      - C:\Users\ABagryanov\DockerShare\otus\home_work_9:/var/lib/mysql
      - .\init.sql:/init.sql
      - .\custom.conf:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "3309:3306"

  mysql-db-admin:
    image: adminer:4.8.1
    ports:
      - 80:8080

volumes:
  home_work_9:


