CREATE USER otus WITH ENCRYPTED PASSWORD 'otus';
CREATE DATABASE otus_internet_shop OWNER otus;
\connect otus_internet_shop;
CREATE SCHEMA IF NOT EXISTS company AUTHORIZATION otus;
CREATE SCHEMA IF NOT EXISTS product AUTHORIZATION otus;
CREATE SCHEMA IF NOT EXISTS customer AUTHORIZATION otus;
CREATE SCHEMA IF NOT EXISTS supplier AUTHORIZATION otus;